spring:
  datasource:
    username: root
    password: chai19980618
    url: jdbc:mysql://localhost:3306/tcrush?&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      tcrush:
        dao:
          debug